# See https://github.com/excelwebzone/EWZRecaptchaBundle for full configuration
ewz_recaptcha:
    enabled: true
    public_key:  '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    private_key: '%env(GOOGLE_RECAPTCHA_SECRET)%'
    locale_key: '%kernel.default_locale%'
    version: 3
